// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCKrxnUqI4PgnfTzPAyvVIRjTxAGTKrr8',
    appId: '1:420229068360:web:726d805134a4b7743d8a7d',
    messagingSenderId: '420229068360',
    projectId: 'refranero-5e0b2',
    authDomain: 'refranero-5e0b2.firebaseapp.com',
    databaseURL: 'https://refranero-5e0b2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'refranero-5e0b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN7AEP4guwqf_SuUBLIQh7DYo0tDBE2iQ',
    appId: '1:420229068360:android:5f010082ebc319633d8a7d',
    messagingSenderId: '420229068360',
    projectId: 'refranero-5e0b2',
    databaseURL: 'https://refranero-5e0b2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'refranero-5e0b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2buiJNcx_7KPj7JrhY12b7plp9yBkg2M',
    appId: '1:420229068360:ios:2adae59385a218a63d8a7d',
    messagingSenderId: '420229068360',
    projectId: 'refranero-5e0b2',
    databaseURL: 'https://refranero-5e0b2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'refranero-5e0b2.appspot.com',
    androidClientId: '420229068360-bf7752vbaotc66a1c3qkkqpm12ddetdf.apps.googleusercontent.com',
    iosClientId: '420229068360-20l0ei59bunrbodct4mf4986lsbgpd2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.refraneroApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2buiJNcx_7KPj7JrhY12b7plp9yBkg2M',
    appId: '1:420229068360:ios:900a1bf03e5870a83d8a7d',
    messagingSenderId: '420229068360',
    projectId: 'refranero-5e0b2',
    databaseURL: 'https://refranero-5e0b2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'refranero-5e0b2.appspot.com',
    androidClientId: '420229068360-bf7752vbaotc66a1c3qkkqpm12ddetdf.apps.googleusercontent.com',
    iosClientId: '420229068360-dge34jk2p9crd6r0tuca6v3d27m04fqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.refraneroApp.RunnerTests',
  );
}
